### ISSUE TITLE
删除消息，撤回消息接口调完之后，再去调用获取历史消息，仍然可以获取到

### ISSUE THREAD

**Issue by 627171314** [jpush/jmessage-flutter-plugin#129]
这两个接口：
jmessage.retractMessage(target: type, serverMessageId: messageId);
jmessage.deleteMessageById(type: type, messageId: messageId);

调用完，再调用获取历史消息接口：
jmessage.getHistoryMessages(type: type, from: from, limit: limit, isDescend: false);
仍然能获取到被删除或被撤回的消息

**Comment by suyie001** [comment]
我这边是撤回消息后 再调用jmessage.getHistoryMessages会因为又Null，导致整个历史消息获取失败。极光这都不咋更新 感觉废了

**Comment by suyie001** [comment]
E/flutter (13435): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (13435): #0      JMNormalMessage.generateMessageFromJson (package:jmessage_flutter/jmessage_flutter.dart:2041:70)
E/flutter (13435): #1      JmessageFlutter.getHistoryMessages (package:jmessage_flutter/jmessage_flutter.dart:893:35)

**Comment by lostcixin** [comment]
你解决了吗
