### ISSUE TITLE
getConversations() 拉取到自定义消息, 安卓抛出异常,iOS 正常

### ISSUE THREAD

**Issue by lalaMiao** [jpush/jmessage-flutter-plugin#34]

**Comment by lalaMiao** [comment]
PlatformException(error, Unsupported value: {"atext":"娃安徽啊啊","content_text":"[自定义消息]"}, null)

**Comment by lalaMiao** [comment]
类似上面,那种

**Comment by fcloud89** [comment]
我也遇到了，jmessage_flutter: "^0.0.15"版本，
安卓工程实际引入的是
'cn.jiguang.sdk:jmessage:2.8.2'
'cn.jiguang.sdk:jcore:1.2.7'

发送自定义消息后，

**Comment by fcloud89** [comment]
我也遇到了，jmessage_flutter: "^0.0.15"版本，
安卓工程实际引入的是
'cn.jiguang.sdk:jmessage:2.8.2'
'cn.jiguang.sdk:jcore:1.2.7'

发送自定义消息后，
W/JIGUANG-JMessage(27585): [CommonUtils] error occurred in users callback, msg = Unsupported value: {"extras":"{\"name\":\"买了佛冷\"}"}
W/System.err(27585): java.lang.IllegalArgumentException: Unsupported value: {"extras":"{\"name\":\"买了佛冷\"}"}
W/System.err(27585): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:289)
W/System.err(27585): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:286)
W/System.err(27585): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
W/System.err(27585): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
W/System.err(27585): 	at com.jiguang.jmessageflutter.JMessageUtils.handleResult(JMessageUtils.java:51)
W/System.err(27585): 	at com.jiguang.jmessageflutter.JMessageUtils$1.gotResult(JMessageUtils.java:170)
W/System.err(27585): 	at cn.jpush.im.api.BasicCallback.gotResult(Unknown Source:0)
W/System.err(27585): 	at cn.jmessage.biz.k.b.c(Unknown Source:0)
W/System.err(27585): 	at cn.jmessage.biz.k.b.b(Unknown Source:0)
W/System.err(27585): 	at cn.jmessage.biz.k.b$2.call(Unknown Source:8)
W/System.err(27585): 	at cn.jmessage.a.a.e$2.run(Unknown Source:4)
W/System.err(27585): 	at android.os.Handler.handleCallback(Handler.java:873)
W/System.err(27585): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(27585): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(27585): 	at android.app.ActivityThread.main(ActivityThread.java:6981)
W/System.err(27585): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27585): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(27585): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by fcloud89** [comment]
@huangminlinux @fendouai @javenfang

**Comment by fcloud89** [comment]
@huangminlinux @fendouai @javenfang 
上述问题定位于插件的安卓lib工程内的JsonUtils.java文件297行，
result.put("customObject", toJson(customObject));
其中 toJson(customObject)报错
