### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(871303, Invalid username., )

### ISSUE THREAD

**Issue by ChenQuan** [jpush/jmessage-flutter-plugin#40]
```
E/flutter ( 7080): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(871303, Invalid username., )
E/flutter ( 7080): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 7080): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 7080): <asynchronous suspension>
E/flutter ( 7080): #2      JmessageFlutter.login (package:jmessage_flutter/jmessage_flutter.dart:271:20)
E/flutter ( 7080): <asynchronous suspension>
E/flutter ( 7080): #3      _LoginState._login (package:im/page/login.dart:24:20)
E/flutter ( 7080): #4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
E/flutter ( 7080): #5      _LoginState._login (package:im/page/login.dart:20:9)
E/flutter ( 7080): #6      _LoginState.build.<anonymous closure> (package:im/page/login.dart:75:17)
E/flutter ( 7080): #7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
E/flutter ( 7080): #8      _LoginState.build.<anonymous closure> (package:im/page/login.dart:65:24)
E/flutter ( 7080): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 7080): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 7080): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 7080): #12     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 7080): #13     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 7080): #14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 7080): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 7080): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 7080): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7080): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7080): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7080): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 7080): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7080): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7080): #23     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 7080): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 7080): 
```
调用者两个方法时，都会出错
```
.login(username: username, password: password);
.userRegister(username: username, password: password);
```

flutter version:1.5
jmessage-flutter-plugin: 0.0.16

**Comment by ChenQuan** [comment]
@huangminlinux 找到了报错的原因。

- `.login(username: username, password: password);`是因为用户名没有注册，所以显示` Invalid username`

- `.userRegister(username: username, password: password);`是因为注册用户时，用户名和密码不符合要求（要求用户名和密码都必须`大于4个字符`）。

建议使用更人性化的错误提示，或者一开始就说明这种情况，让开发者自己做个性化处理。
