### ISSUE TITLE
Android创建会话后发消息报错

### ISSUE THREAD

**Issue by zhangtengchao** [jpush/jmessage-flutter-plugin#46]
E/flutter (31077): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(898002, [nihfuskdjahfoijhasfljnwolketn], )
E/flutter (31077): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (31077): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (31077): <asynchronous suspension>
E/flutter (31077): #2      JmessageFlutter.sendTextMessage (package:jmessage_flutter/jmessage_flutter.dart:468:33)
E/flutter (31077): <asynchronous suspension>
E/flutter (31077): #3      IMProvide.sendText (package:school_recruit/provide/provide_im.dart:62:14)
E/flutter (31077): #4      _ChatPageState._operation.<anonymous closure> (package:school_recruit/pages/im/page_chat.dart:111:51)
E/flutter (31077): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter (31077): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter (31077): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter (31077): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter (31077): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
E/flutter (31077): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter (31077): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (31077): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (31077): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
E/flutter (31077): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter (31077): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (31077): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (31077): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (31077): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (31077): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31077): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (31077): #21     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter (31077): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)

请问这是什么错误？

**Comment by zhangtengchao** [comment]
实际消息已经发送成功了，之后getHistoryMessages中可以获取该消息
