### ISSUE TITLE
android release下init异常

### ISSUE THREAD

**Issue by mrcwl** [jpush/jmessage-flutter-plugin#79]
2019-10-27 14:45:51.909 4616-4616/? E/MethodChannel#jmessage_flutter: Failed to handle method call
    b.a.a.b.g: Subscriber class b.a.c.h.a has no public methods called onEvent
        at b.a.a.b.n.a(Unknown Source:347)
        at b.a.a.b.e.b(Unknown Source:7)
        at b.a.a.b.e.a(Unknown Source:0)
        at b.a.c.c.a.a(Unknown Source:22)
        at b.a.c.c.a(Unknown Source:60)
        at cn.jpush.im.android.api.JMessageClient.init(Unknown Source:69)
        at com.jiguang.jmessageflutter.Fa.za(:7)
        at com.jiguang.jmessageflutter.Fa.a(:6)
        at d.a.b.a.o$a.a(:2)
        at io.flutter.embedding.engine.a.c.a(:16)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:8113)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

debug模式下正常。

flutter doctor --android-licenses[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A602, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.39.2)
[✓] Proxy Configuration
[✓] Connected device (2 available)

• No issues found!

**Comment by mrcwl** [comment]
@raoxudong

**Comment by hlj2722** [comment]
我也遇到同样的问题
--------------------------------------
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.5)
[√] Connected device (2 available)
------------------------------------------------------------
Launching lib\main.dart on MI CC 9 in release mode...
I/flutter (19834): | Example | Flutter | demo manin init state
I/flutter (19834): add listener receive ReceiveMessage
E/flutter (19834): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Subscriber class b.a.c.j.a has no public methods called onEvent, null)
E/flutter (19834): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (19834): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (19834): <asynchronous suspension>
E/flutter (19834): #2      JmessageFlutter.init (package:jmessage_flutter/jmessage_flutter.dart:277)
E/flutter (19834): #3      _MyHomePageState.initState (package:jmessage_demo/main.dart:73)
E/flutter (19834): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355)
E/flutter (19834): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (19834): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
E/flutter (19834): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (19834): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (19834): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (19834): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (19834): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
E/flutter (19834): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
E/flutter (19834): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (19834): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (19834): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (19834): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
E/flutter (19834): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (19834): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
E/flutter (19834): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
E/flutter (19834): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (19834): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (19834): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
E/flutter (19834): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
E/flutter (19834): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
E/flutter (19834): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
E/flutter (19834): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
E/flutter (19834): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
E/flutter (19834): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
E/flutter (19834): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)

**Comment by MrFanco** [comment]
wo也遇到了 这个问题
